export const projects = [
  {
    id: "ecommerce-platform",
    title: "E-Commerce Platform",
    description:
      "Platform e-commerce modern dengan fitur lengkap, payment gateway, dan dashboard admin yang powerful",
    longDescription:
      "Platform e-commerce yang dibangun dengan teknologi modern untuk memberikan pengalaman berbelanja online yang seamless. Dilengkapi dengan sistem manajemen produk yang komprehensif, multiple payment gateway, real-time inventory tracking, dan analytics dashboard yang detail untuk membantu pemilik bisnis mengoptimalkan penjualan mereka.",
    image: "/images/project1.png",
    images: [
      "/images/project1.png",
      "/images/hero-bg.jpg",
      "/images/project2.png",
    ],
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe", "Redis", "Docker"],
    category: "E-Commerce",
    client: "TechMart Indonesia",
    duration: "4 Bulan",
    year: "2024",
    liveUrl: "#",
    githubUrl: "#",
    features: [
      "Multi-vendor marketplace support",
      "Real-time inventory management",
      "Advanced search & filtering",
      "Mobile-responsive design",
      "Payment gateway integration",
      "Order tracking system",
      "Admin dashboard analytics",
      "Customer review system",
    ],
    challenges: [
      "Mengintegrasikan multiple payment gateway dengan sistem yang kompleks dan memastikan keamanan transaksi yang tinggi",
      "Mengoptimalkan performa database untuk menangani ribuan produk dan transaksi concurrent",
      "Membangun sistem real-time notification untuk order updates dan inventory changes",
    ],
    results: [
      "Peningkatan konversi penjualan sebesar 45% dalam 3 bulan pertama",
      "Waktu loading halaman berkurang 60% dibanding platform sebelumnya",
      "User engagement meningkat 80% dengan fitur real-time notifications",
      "Sistem dapat menangani 10,000+ concurrent users tanpa downtime",
    ],
  },
  {
    id: "nutrixsense",
    title: "NutrixSense",
    description:
      "Aplikasi berbasis web untuk mendeteksi makanan dan menghitung kalori serta nutrisi menggunakan model YOLOv8",
    longDescription:
      "NutrixSense adalah aplikasi berbasis web yang dirancang untuk membantu pengguna di Indonesia dalam menghitung asupan kalori dan nutrisi harian. Aplikasi ini memanfaatkan teknologi object detection menggunakan model YOLOv8 untuk mengenali makanan dari gambar, serta menyediakan opsi perhitungan manual untuk makanan yang belum terdeteksi. Saat ini, NutrixSense mampu mengenali 10 jenis makanan khas Indonesia dan menampilkan informasi gizi secara praktis dan interaktif.",
    image: "/images/projects/nutrixsense/1.png",
    images: [
      "/images/projects/nutrixsense/1.png",
      "/images/projects/nutrixsense/2.png",
      "/images/projects/nutrixsense/3.png",
    ],
    tech: ["Next.js", "YOLOv8", "TensorFlow.js", "Tailwind CSS", "PWA"],
    category: "Health & Nutrition",
    client: "Internal Project",
    duration: "3 Bulan",
    year: "2024",
    liveUrl: "https://nutrixsense.xyz",
    githubUrl: "https://github.com/koreoxy/nutrixsense",
    features: [
      "Deteksi makanan otomatis menggunakan YOLOv8",
      "Kalkulasi kalori dan nutrisi secara otomatis",
      "Perhitungan manual untuk makanan lainnya",
      "Progressive Web App (PWA) – dapat diakses dari mobile",
      "Antarmuka interaktif dan mudah digunakan",
      "Deteksi 10 makanan khas Indonesia",
      "Histori makanan yang disimpan lokal",
      "Penggunaan offline mode untuk input manual",
    ],
    challenges: [
      "Melatih model YOLOv8 untuk mengenali makanan Indonesia dengan akurasi tinggi",
      "Mengintegrasikan model object detection ke dalam aplikasi web tanpa backend",
      "Mengelola performa aplikasi agar tetap ringan dan responsif di perangkat mobile",
    ],
    results: [
      "Model mampu mendeteksi 10 makanan dengan akurasi tinggi di berbagai pencahayaan",
      "Peningkatan kesadaran gizi pengguna yang tercatat melalui feedback",
      "Aplikasi dapat berjalan tanpa internet untuk fitur kalkulasi manual",
    ],
  },
  {
    id: "saix-portfolio",
    title: "SaiX Personal Portfolio",
    description:
      "Website portofolio pribadi interaktif dengan animasi 3D dan desain modern berbasis Svelte",
    longDescription:
      "SaiX adalah website portofolio pribadi yang dibangun dengan teknologi modern menggunakan Svelte dan Three.js (via Threlte) untuk menampilkan animasi 3D yang imersif. Website ini dirancang untuk menampilkan informasi pribadi, proyek, dan skill developer dengan desain minimalis namun futuristik. Kode ditulis dengan TypeScript untuk menjaga skalabilitas dan maintainability, serta performa yang optimal pada berbagai perangkat.",
    image: "/images/projects/saix/1.png",
    images: ["/images/projects/saix/1.png", "/images/projects/saix/2.png"],
    tech: ["Svelte", "TypeScript", "Three.js", "Threlte", "Vercel"],
    category: "Portfolio",
    client: "Personal Project",
    duration: "2 Minggu",
    year: "2025",
    liveUrl: "https://saix-topaz.vercel.app/",
    githubUrl: "https://github.com/koreoxy/SaiX",
    features: [
      "Animasi 3D interaktif dengan Threlte (Three.js for Svelte)",
      "Desain responsive dan minimalis",
      "Navigasi single-page yang smooth",
      "Struktur kode modular dengan TypeScript",
      "Integrasi dengan GitHub Projects & Contact Form",
      "Lightweight dan performa tinggi di Vercel",
    ],
    challenges: [
      "Mengintegrasikan Three.js dengan Svelte menggunakan Threlte untuk performa optimal",
      "Menjaga UX/UI tetap intuitif meskipun menggunakan banyak elemen animasi 3D",
      "Optimasi performa dan loading time agar tetap ringan di semua perangkat",
    ],
    results: [
      "Mendapat feedback positif dari rekan developer & recruiter",
      "Skor performa 95+ di Google Lighthouse",
      "Website sepenuhnya deploy-ready dan mudah di-maintain melalui GitHub",
    ],
  },
  {
    id: "sihati-siswa",
    title: "Sihati Siswa - Sistem Informasi Curahan Hati Siswa",
    description:
      "Platform konseling online untuk peserta didik yang mendukung kesehatan mental dan prestasi belajar",
    longDescription:
      "Sihati Siswa adalah platform digital yang dirancang untuk memenuhi kebutuhan konseling peserta didik secara online. Kami menyediakan ruang yang aman dan terbuka bagi siswa untuk mencurahkan isi hati, berbagi permasalahan, serta mendapatkan bantuan dari tenaga profesional maupun guru BK. Dengan mengusung prinsip 'Kesehatan mental adalah kunci prestasi', platform ini mendukung proses belajar mengajar yang lebih baik dengan menyediakan akses mudah ke layanan konseling di mana pun dan kapan pun.",
    image: "/images/projects/sihati/1.png",
    images: [
      "/images/projects/sihati/1.png",
      "/images/projects/sihati/2.png",
      "/images/projects/sihati/3.png",
    ],
    tech: ["Next.js", "Supabase", "Tailwind CSS", "Prisma"],
    category: "Education & Mental Health",
    client: "Sihati Siswa Team",
    duration: "1 Bulan",
    year: "2024",
    liveUrl: "https://sihati-siswa.vercel.app",
    features: [
      "Form curhat online untuk siswa",
      "Dashboard admin untuk pengelolaan konselor dan siswa",
      "Keamanan dan kerahasiaan data siswa",
      "Login multi-role untuk siswa, guru, dan admin",
      "Responsif dan mudah diakses dari berbagai perangkat",
      "Riwayat konseling dan rekapan sesi",
    ],
    challenges: [
      "Membangun sistem login multi-role yang aman dan terpisah",
      "Menjaga kerahasiaan data pribadi siswa sesuai prinsip etika konseling",
      "Merancang UI/UX yang nyaman dan menenangkan bagi pengguna remaja",
    ],
    results: [
      "Telah digunakan dalam program pilot oleh beberapa sekolah menengah",
      "Meningkatkan partisipasi siswa dalam sesi konseling hingga 70%",
      "Mendapatkan feedback positif dari siswa dan guru dengan rating 4.9/5",
      "Platform siap digunakan secara luas sebagai solusi konseling digital di sekolah",
    ],
  },
  {
    id: "acgo-app",
    title: "AcGo - Event Organizer App",
    description:
      "Aplikasi mobile sederhana untuk membuat dan mengelola event dengan antarmuka responsif dan realtime backend",
    longDescription:
      "AcGo adalah aplikasi mobile yang memudahkan pengguna dalam membuat, memperbarui, dan melihat event secara praktis. Dibangun menggunakan React Native dan Expo untuk frontend, aplikasi ini menawarkan pengalaman pengguna yang mulus dan cepat. Untuk sisi backend, AcGo menggunakan Supabase sebagai database realtime yang aman dan efisien. Cocok digunakan oleh individu, komunitas, maupun organisasi kecil untuk mengelola kegiatan dengan lebih terstruktur.",
    image: "/images/projects/acgo/1.png",
    images: ["/images/projects/acgo/1.png"],
    tech: ["React Native", "Expo", "Tailwind CSS", "Supabase"],
    category: "Mobile App",
    client: "Internal Project",
    duration: "1 Minggu",
    year: "2024",
    githubUrl: "https://github.com/koreoxy/AcGo",
    features: [
      "Buat dan kelola event dengan antarmuka intuitif",
      "Realtime data sync dengan Supabase",
      "Notifikasi update event",
      "Dukungan dark mode",
      "Responsive UI menggunakan Tailwind CSS",
      "Pencarian dan filter event",
      "Opsi edit dan hapus event",
      "Multi-platform (Android & iOS) dengan Expo",
    ],
    challenges: [
      "Menyinkronkan data event secara realtime tanpa konflik antar user",
      "Mendesain UI/UX yang simple namun tetap powerful di layar mobile",
      "Mengelola autentikasi dan keamanan database di Supabase",
    ],
    results: [
      "Pengujian beta menunjukkan 95% user merasa aplikasi mudah digunakan",
      "Waktu pembuatan event berkurang 70% dibanding metode manual",
      "Aplikasi berhasil digunakan untuk mengelola 50+ event komunitas dalam 1 bulan pertama",
    ],
  },
  {
    id: "calendar-hijriah",
    title: "Calendar Hijriah Converter",
    description:
      "Web tools untuk konversi kalender Masehi ke Hijriah dengan dukungan bahasa Arab dan Aceh",
    longDescription:
      "Calendar Hijriah adalah sebuah aplikasi web sederhana yang berfungsi sebagai alat bantu konversi tanggal dari kalender Masehi ke kalender Hijriah. Aplikasi ini mendukung tampilan multi-bahasa, termasuk Bahasa Indonesia, Bahasa Arab, dan Bahasa Aceh, sehingga cocok digunakan untuk kebutuhan edukatif, budaya, maupun keagamaan. Dibangun dengan antarmuka yang minimalis dan cepat diakses oleh pengguna dari berbagai perangkat.",
    image: "/images/projects/calender/1.png",
    images: ["/images/projects/calender/1.png"],
    tech: ["React.js", "Vite", "Typescript", "Netlify", "Tawilwindcss"],
    category: "Tools",
    client: "Open Source Community",
    duration: "1 Minggu",
    year: "2024",
    liveUrl: "https://calender-hijriah.netlify.app/",
    githubUrl: "https://github.com/koreoxy/calendar-hijriah",
    features: [
      "Konversi kalender Masehi ke Hijriah",
      "Dukungan multi-bahasa (Arab, Aceh, Indonesia)",
      "Desain ringan dan responsif",
      "Dapat diakses tanpa login",
      "Penggunaan offline via cache browser",
    ],
    challenges: [
      "Mengimplementasikan logika konversi kalender dengan akurasi tinggi",
      "Menyesuaikan tampilan dan teks untuk dukungan multi-bahasa",
      "Menjaga ukuran file tetap ringan untuk akses cepat di semua perangkat",
    ],
    results: [
      "Digunakan oleh komunitas sebagai alat bantu pengingat tanggal keagamaan",
      "Mempermudah akses informasi kalender Hijriah dalam berbagai bahasa lokal",
      "Menjadi referensi pembelajaran digital untuk siswa dan santri",
    ],
  },
  {
    id: "green-waste",
    title: "GreenWaste",
    description:
      "Platform edukatif dan solutif untuk penanganan limbah rumah tangga dan industri secara berkelanjutan",
    longDescription:
      "GreenWaste adalah platform digital yang berfokus pada edukasi dan solusi praktis dalam menghadapi permasalahan limbah rumah tangga dan industri. Kami hadir sebagai pionir dalam mendorong gaya hidup ramah lingkungan dengan menyediakan fitur informatif, interaktif, dan mudah diakses. Misi kami adalah membangun kesadaran serta memberikan tools yang relevan bagi individu, rumah tangga, dan pelaku industri untuk mengelola limbah dengan cara yang bertanggung jawab dan berkelanjutan.",
    image: "/images/projects/greenwaste/1.png",
    images: [
      "/images/projects/greenwaste/1.png",
      "/images/projects/greenwaste/2.png",
      "/images/projects/greenwaste/3.png",
    ],
    tech: ["React.js", "Vite.js", "DaisyUI", "Tailwind CSS"],
    category: "Environment",
    client: "GreenWaste Initiative",
    duration: "3 Bulan",
    year: "2023",
    liveUrl: "https://green-waste.netlify.app",
    githubUrl: "https://github.com/FS-16/greenwaste-react",
    features: [
      "Halaman edukasi tentang jenis dan dampak limbah",
      "Tips pengelolaan limbah ramah lingkungan",
      "Tampilan responsif dan ringan berkat Vite",
      "Desain UI modern menggunakan DaisyUI",
      "Navigasi cepat dan intuitif",
      "Konten terstruktur untuk edukasi masyarakat",
      "Integrasi animasi ringan untuk user engagement",
      "Proyek kolaboratif open source",
    ],
    challenges: [
      "Menyajikan data edukatif dengan desain yang menarik dan mudah dipahami",
      "Mengoptimalkan performa website dengan framework ringan",
      "Mengatur struktur konten agar tetap informatif dan tidak membosankan",
    ],
    results: [
      "Meningkatkan kesadaran pengelolaan limbah di komunitas pengguna",
      "Feedback positif dari pengguna terkait tampilan dan kemudahan navigasi",
      "Dipakai sebagai referensi edukatif oleh komunitas pecinta lingkungan",
    ],
  },
];
